version: '3.3'
services:
  postgredb:
    container_name: postgredb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
 
  web:
    build: .
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    links:
      - "postgredb:database"
      
