version: '3.3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - postgredb
  postgredb:
    container_name: postgredb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "postgredb:5432"
    networks:
      - default
      - service-proxy
      

networks:
  default:
    name: postgre-service_default